name: UploadTestflight

on:
  push:
    branches: [develop]

jobs:
  upload_testflight:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 14.2.0

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          repository: chatty-lab/Chatty-iOS-fastlane-certificate
          path: Projects/App/Config
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Setting Master Key
        run: |
          echo "$MASTER_KEY" > Tuist/master.key
        env:
          MASTER_KEY: ${{secrets.MASTER_KEY}}

      - name: Install Tuist
        run: curl -Ls https://install.tuist.io|bash

      - name: Install Fastlane
        run: brew install fastlane

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Tuist clean
        run: tuist clean

      - name: Tuist fetch
        run: tuist fetch

      - name: Log Pre-Decrypt Certificate File Details
        run: ls -l ./Tuist/Signing/development.cer.encrypted

      - name: Output Master Key
        run: |
          cat Tuist/master.key

      - name: Tuist Signing Decrypt
        run: tuist signing decrypt

      - name: Log Post-Decrypt Certificate File Details
        run: ls -l ./Tuist/Signing/development.cer

      - name: Set Keychain
        run: fastlane set_keychain
        env:
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Verify Certificate File
        run: openssl x509 -in ./Tuist/Signing/development.cer -text -noout

      - name: Log Certificate File Details
        run: ls -l ./Tuist/Signing/development.cer

      - name: Tuist generate
        run: tuist generate

      - run: fastlane tf
        env:
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
